version: '3'
services:
 mysql:
  image: mysql:5.7
  command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
  container_name: mysql
  ports:
    - 3306:3306
  volumes:
    - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
    - ./mysql_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: mysql
    MYSQL_DATABASE: test_db
    MYSQL_USER: user
    MYSQL_PASSWORD: password
